{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.pipelineNamespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: [""]
  resources: ["secrets", "pods", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterdeployments", "machinepools"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: ["hypershift.openshift.io"]
  resources: ["hostedclusters", "nodepools"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: ["hypershift.openshift.io"]
  resources: ["hostedclusters/finalizers"]
  verbs: ["update", "patch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters/accept"]
  verbs: ["update", "patch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclustersets"]
  verbs: ["get", "list"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclustersets/join"]
  verbs: ["create"]
{{- if eq (include "pipelines.klusterletAddonEnabled" . | trim) "true" }}
- apiGroups: ["agent.open-cluster-management.io"]
  resources: ["klusterletaddonconfigs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
{{- end }}
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions"]
  verbs: ["get"]
- apiGroups: ["legion.io"]
  resources: ["legionclusters", "xlegionclusters", "legionnodepools", "xlegionnodepools"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.pipelineNamespace }}
