apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: interop-test
  namespace: {{ .Values.qeCIPipelines.defaults.namespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  description: Run pattern interop tests
  params:
    - name: hub-cluster-name
      type: string
      default: ""
    - name: spoke-cluster-name
      type: string
      default: ""
    - name: spoke-secondary-cluster-name
      type: string
      default: ""
    - name: install-status
      type: string
      default: "success"
    - name: target-clustergroup
      type: string
      default: hub
  workspaces:
    - name: pattern-repo
    - name: kubeconfig
  results:
    - name: outcome
  steps:
    - name: run-interop-pattern-test
      image: {{ .Values.qeCIPipelines.defaults.utilityContainerImg }}
      env:
        - name: VP_HUBCONFIG
          value: $(workspaces.kubeconfig.path)/$(params.hub-cluster-name)-kubeconfig
        - name: VP_SPOKECONFIG
          value: $(workspaces.kubeconfig.path)/$(params.spoke-cluster-name)-kubeconfig
        - name: VP_SPOKECONFIG_SECONDARY
          value: $(workspaces.kubeconfig.path)/$(params.spoke-secondary-cluster-name)-kubeconfig
        - name: TARGET_CLUSTERGROUP
          value: $(params.target-clustergroup)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        INSTALL_STATUS=$(params.install-status)

        if [ "$INSTALL_STATUS" != "success" ]; then
          echo "Skipping interop test due to failed install/import"
          echo -n "skipped" > $(results.outcome.path)
          exit 0
        fi

        trap 'echo -n "failed" > $(results.outcome.path)' ERR
        cd $(workspaces.pattern-repo.path)

        ./pattern.sh make run-ci-tests

        # If we reach here, everything succeeded
        echo -n success > "$(results.outcome.path)"